# Parameters
parameters:
    assetic.controller.class: FLM\UberstrapBundle\Controller\AsseticController
    assetic.asset_factory.class: FLM\UberstrapBundle\Assetic\Factory\AssetFactory
    test.client.class: FLM\UberstrapBundle\Tests\Client
    flm_uberstrap.fixtures: %kernel.root_dir%/Resources/fixtures.yml

# Twig Configuration
twig:
    form:
        resources:
            - FLMUberstrapBundle:Form:bootstrap.html.twig

# Assetic Configuration
assetic:
    node_paths: [/usr/lib/node_modules]
    node: /usr/bin/nodejs
    workers:
        cache_busting: ~
    filters:
        cssrewrite: ~
        phpcssembed: ~
        less:
            apply_to: "\.less$"
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/Resources/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../components/bootstrap/js/bootstrap.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/bootstrap.js
        jquery:
            inputs:
                - %kernel.root_dir%/../components/jquery/jquery.js
            output: js/jquery.js
        select2_css:
            inputs:
                - %kernel.root_dir%/../components/select2/select2.css
                - %kernel.root_dir%/../components/select2/select2-bootstrap.css
            filters:
                - phpcssembed
            output: css/select2.css
        select2_js:
            inputs:
                - %kernel.root_dir%/../components/select2/select2.js
            output: js/select2.js
        flmuber_select2_css:
            inputs:
                - %kernel.root_dir%/../vendor/flm/uberstrap-bundle/FLM/UberstrapBundle/Resources/less/select2/*.less
            output: css/flmuber_select2.css
            filters:
                - less
                - cssrewrite

# Doctrine Configuration
doctrine:
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            anh_taggable: { mapping: false }
            taggable:
                type: annotation
                alias: AnhTaggable
                prefix: Anh\Taggable\Entity\MappedSuperclass
                dir: "%kernel.root_dir%/../vendor/anh/doctrine-extensions-taggable/lib/Anh/Taggable/Entity/MappedSuperclass"

# BraincraftedBootstrapBundle Configuration
braincrafted_bootstrap:
     assets_dir: %kernel.root_dir%/../components/bootstrap
     jquery_path: %kernel.root_dir%/../components/jquery
     less_filter: less
     customize:
         variables_file: %kernel.root_dir%/Resources/less/variables.less
         bootstrap_template: FLMUberstrapBundle:Bootstrap:bootstrap.less.twig
     auto_configure:
         assetic: false
         twig: false

# JMSDiExtraBundle Configuration
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [ FLMUberstrapBundle ]
        directories: ["%kernel.root_dir%/../src"]

# UsuScryptPasswordEncoderBundle
usu_scrypt_password_encoder:
    cpu_cost: 2048
    memory_cost: 4
    parallelization_cost: 1
    key_length: 128

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FLM\UberstrapBundle\Entity\User
